# This workflow is named "Deploy to AWS (env3)" and triggers on pushes to the main branch or manual dispatch.
name: Deploy to AWS (env3)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_env3:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repository code to the GitHub Actions runner.
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Configure AWS credentials using the secrets stored in the GitHub repository settings.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # Provide AWS credentials from GitHub Secrets and set the default AWS region.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3) Install or update the AWS CLI on the runner to ensure we have a recent version.
      - name: Install or Update AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          # Run the installer with --update to upgrade any existing AWS CLI installation.
          sudo ./aws/install --update
          aws --version

      # 4) Create an S3 bucket for env3. This command will fail if the bucket already exists with the same name.
      - name: Create S3 bucket
        run: |
          aws s3api create-bucket --bucket cicdproj-calls-env3 --region us-east-1

      # 5) Create "prefixes" (folders) within the S3 bucket for storing landing_zone and processed.
      - name: Create S3 prefixes
        run: |
          aws s3api put-object --bucket cicdproj-calls-env3 --key landing_zone/
          aws s3api put-object --bucket cicdproj-calls-env3 --key processed/

      # 6) Check if the DynamoDB table exists; if not, create it. 
      - name: Create DynamoDB table if not exists
        run: |
          if aws dynamodb describe-table --table-name cicdproj_calls_bronze_env3; then
            echo "Table cicdproj_calls_bronze_env3 already exists. Skipping creation."
          else
            echo "Table does not exist. Creating now..."
            aws dynamodb create-table \
              --table-name cicdproj_calls_bronze_env3 \
              --attribute-definitions AttributeName=ip,AttributeType=S AttributeName=timestamp,AttributeType=N \
              --key-schema AttributeName=ip,KeyType=HASH AttributeName=timestamp,KeyType=RANGE \
              --billing-mode PAY_PER_REQUEST \
              --region us-east-1
          fi

      # 7) Repeat the same check-and-create process for the DynamoDB table, effectively a duplicate step.
      - name: Create DynamoDB table if not exists
        run: |
          if aws dynamodb describe-table --table-name cicdproj_calls_bronze_env3; then
            echo "Table cicdproj_calls_bronze_env3 already exists. Skipping creation."
          else
            echo "Table does not exist. Creating now..."
            aws dynamodb create-table \
              --table-name cicdproj_calls_bronze_env3 \
              --attribute-definitions AttributeName=ip,AttributeType=S AttributeName=timestamp,AttributeType=N \
              --key-schema AttributeName=ip,KeyType=HASH AttributeName=timestamp,KeyType=RANGE \
              --billing-mode PAY_PER_REQUEST \
              --region us-east-1
          fi

    # 8) Build the Lambda zip file, which includes both data/bronze and data/common folders.
      - name: Build Lambda zip
        run: |
          pip install --upgrade -r data/bronze/requirements.txt -t data/bronze/libs
          zip -r data/bronze/function.zip data/bronze data/common -x '*/__pycache__/*'
          echo "Contents of the ZIP file:"
          unzip -l data/bronze/function.zip

      # 9) Create or update the Lambda function code. If it exists, we update its code; otherwise, we create a new function.
      - name: Deploy Lambda function (create or update)
        run: |
          FUNCTION_NAME="cicdproj_calls_bronze_env3"
          if aws lambda get-function --function-name $FUNCTION_NAME 2>/dev/null; then
            echo "Updating Lambda code and config for $FUNCTION_NAME ..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://data/bronze/function.zip \
              --region us-east-1

          # Wait until AWS reports the function update is complete
          aws lambda wait function-updated --function-name $FUNCTION_NAME --region us-east-1
            
            # IMPORTANT: if the function was originally created with a different handler,
            # we need to update it so that it looks for data.bronze.handler.lambda_handler
            aws lambda update-function-configuration \
              --function-name $FUNCTION_NAME \
              --handler data.bronze.handler_lambda_handler \
              --region us-east-1
          else
            echo "Creating Lambda function $FUNCTION_NAME ..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime python3.12 \
              --role arn:aws:iam::<ACCOUNT_ID>:role/lambda-exec-role-s3-dynamo \
              --handler data.bronze.handler.lambda_handler \
              --zip-file fileb://data/bronze/function.zip \
              --region us-east-1
          fi

      # 10) Remove any existing permission statement for the S3 notification, then add a new one so S3 can invoke this Lambda.
      - name: Remove existing permission if it exists
        run: |
          # This command fails if the statement doesn't exist, so we add '|| true' to ignore the error.
          aws lambda remove-permission \
            --function-name cicdproj_calls_bronze_env3 \
            --statement-id s3notification \
            --region us-east-1 || true
            
      - name: Configure S3 Notification
        run: |
          # 1) Give S3 permission to invoke the Lambda function.
          aws lambda add-permission \
            --function-name cicdproj_calls_bronze_env3 \
            --principal s3.amazonaws.com \
            --action lambda:InvokeFunction \
            --statement-id s3notification \
            --source-arn arn:aws:s3:::cicdproj-calls-env3 \
            --source-account 599224842127 \
            --region us-east-1

          # 2) Create JSON configuration that specifies the S3 event trigger for landing_zone/.json files.
          cat <<EOF > notification_env3.json
          {
            "LambdaFunctionConfigurations": [
              {
                "Id": "cicdproj-calls-env3-notification",
                "LambdaFunctionArn": "arn:aws:lambda:us-east-1:599224842127:function:cicdproj_calls_bronze_env3",
                "Events": ["s3:ObjectCreated:*"],
                "Filter": {
                  "Key": {
                    "FilterRules": [
                      { "Name": "prefix", "Value": "landing_zone/" },
                      { "Name": "suffix", "Value": ".json" }
                    ]
                  }
                }
              }
            ]
          }
          EOF

          # 3) Apply the notification configuration to the S3 bucket, enabling the Lambda trigger.
          aws s3api put-bucket-notification-configuration \
            --bucket cicdproj-calls-env3 \
            --notification-configuration file://notification_env3.json \
            --region us-east-1
