name: Deploy to AWS (env4 via Terraform)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_env4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Build Lambda zip bronze
        run: |
          # Install Python deps into data/bronze/libs
          pip install -r data/bronze/requirements.txt -t data/bronze/libs --upgrade

          # Zip up data/bronze + data/common, excluding __pycache__
          zip -r function.zip data/bronze data/common -x "*/__pycache__/*"
          ls -lh function.zip

      - name: Build Lambda zip api
        run: |
          # Install Python deps into data/api/libs
          pip install -r data/api/requirements.txt -t data/api/libs --upgrade

          # Zip up data/api + data/common, excluding __pycache__
          zip -r function.zip data/api data/common -x "*/__pycache__/*"
          ls -lh function.zip

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
        working-directory: infra
